files: '.py'
exclude: '.git'
default_stages: [pre-commit]

repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 9.0.0a3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
     - id: nbqa-black
       additional_dependencies: [black==26.5.1]
     - id: nbqa-pyupgrade
       additional_dependencies: [pyupgrade==3.21.2]
     - id: nbqa-isort
       additional_dependencies: [isort==8.0.1]
     - id: nbqa-pylint
       additional_dependencies: [pylint==4.0.5]
       args: ["--disable=missing-module-docstring,import-error,wrong-import-position"]
